<a href="https://colab.research.google.com/github/JustynaLL/TEST/blob/master/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [234]:
import pandas as pd
import numpy as np

In [235]:
df = pd.read_csv('/content/Sorted by activity.csv')

In [236]:
staff = pd.read_excel('/content/Stafflisting.xlsx',sheet_name='Sheet1')

In [237]:
staff.sample(5)

,Individual,Name,Office,Practice/BS Group,No. of Records
1005,952822,Florian Jonniaux,Belgium,Antitrust & Foreign Investment Group,1
771,909540,Detlev Schuster,Berlin,Mainstream Corporate,1
1901,929598,Marco Carrieri,Milan,Banking,1
1820,953498,Luis Rodrigo,Madrid,Capital Markets,1
1913,957721,Margarida Alves Borges,Lisbon,Mainstream Corporate,1

In [238]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Activity Date        377 non-null    object
 1   Activity Type        377 non-null    object
 2   Summary              377 non-null    object
 3   Client               377 non-null    object
 4   Client Contacts      346 non-null    object
 5   Linklaters Contacts  308 non-null    object
 6   Sector               369 non-null    object
dtypes: object(7)
memory usage: 20.7+ KB

In [239]:
df.iloc[:,1].unique()

array(['Client Entertainment', 'Client Sponsored Event', 'Employee Added',
       'Employee Update', 'Event - Attended', 'Event - Invited',
       'Newsletter Mailing', 'Relationship Meeting',
       'Training and Seminar - Delivered'], dtype=object)

In [240]:
activities = ['Client Entertainment', 'Client Sponsored Event','Event - Attended','Relationship Meeting','Training and Seminar - Delivered']

In [372]:
df2 = df[df["Activity Type"].isin(activities)].reset_index(drop=True)

In [378]:
df2['Concat'] = df2['Activity Date']+df2['Summary']

In [379]:
df2.head(3)

,Activity Date,Activity Type,Summary,Client,Client Contacts,Linklaters Contacts,Sector,Concat
0,07-07-2022,Client Entertainment,Lunch with Shaalini and Mikhail,Citi Business Services (CBS) Citigroup Centre,"Daya, Shaalini","Shiyan, Mikhail",Banks & Financial Institutions,07-07-2022Lunch with Shaalini and Mikhail
1,07-07-2022,Client Entertainment,Lunch catch-up,Citigroup Inc.,"Lung, Wan Sang","Shen, Thomas",Banks & Financial Institutions,07-07-2022Lunch catch-up
2,14-07-2022,Client Entertainment,Dinner: Noel Hughes and Tommaso Ponsele (Citi),Citigroup Inc.,"Ponsele, Tommaso","Hughes, Noel",Banks & Financial Institutions,14-07-2022Dinner: Noel Hughes and Tommaso Pons...

In [242]:
df3 = df2.assign(Concat = lambda x: df2['Activity Date']+df2['Summary'])

In [243]:
df3['Linklaters Contacts'] = df3['Linklaters Contacts'].fillna('Unknown')
df3['Client Contacts'] = df3['Client Contacts'].fillna('Unknown')

In [277]:
df3_vlookup = df3.copy()
df3_vlookup['Linklaters Contacts'] = df3_vlookup['Linklaters Contacts'].str.split('; ')

In [367]:
PG_dict = {}
PG = []
PG_main = []

for x in df3_vlookup['Linklaters Contacts']:
  for n in range(len(x)):
    x[n] = " ".join(x[n].split(", ")[::-1])
    for index in range(len(staff.Name)):
      if x[n] == staff.Name[index]:
        PG_dict.update({x[n] : staff['Practice/BS Group'][index]})

In [368]:
for x in df3_vlookup['Linklaters Contacts']:
  PG=[]
  for n in range(len(x)):
    PG.append(PG_dict.get(x[n]))
  PG_main.append(set(PG))

In [369]:
df3_vlookup['PG'] = PG_main

In [370]:
df3_vlookup

,Activity Date,Activity Type,Summary,Client,Client Contacts,Linklaters Contacts,Sector,Concat,PG
0,07-07-2022,Client Entertainment,Lunch with Shaalini and Mikhail,Citi Business Services (CBS) Citigroup Centre,"Daya, Shaalini",[Mikhail Shiyan],Banks & Financial Institutions,07-07-2022Lunch with Shaalini and Mikhail,{Banking}
1,07-07-2022,Client Entertainment,Lunch catch-up,Citigroup Inc.,"Lung, Wan Sang",[Thomas Shen],Banks & Financial Institutions,07-07-2022Lunch catch-up,{Capital Markets}
2,14-07-2022,Client Entertainment,Dinner: Noel Hughes and Tommaso Ponsele (Citi),Citigroup Inc.,"Ponsele, Tommaso",[Noel Hughes],Banks & Financial Institutions,14-07-2022Dinner: Noel Hughes and Tommaso Pons...,{Banking}
3,20-07-2022,Client Entertainment,Drinks with Citibank in London,Citibank,"Ellington, Belinda",[Jonathan Ching],Banks & Financial Institutions,20-07-2022Drinks with Citibank in London,{Capital Markets}
4,20-07-2022,Client Entertainment,Drinks with Citibank in London,Citi Business Services (CBS) Citigroup Centre,"Chakhvadze, Aliona; Jigarjian, Elena",[Jonathan Ching],Banks & Financial Institutions,20-07-2022Drinks with Citibank in London,{Capital Markets}
5,21-07-2022,Client Entertainment,Breakfast,Citigroup Global Markets Europe Limited,"Cooke, Colin",[Unknown],Banks & Financial Institutions,21-07-2022Breakfast,{None}
6,22-07-2022,Client Entertainment,Dinner with Citigroup in London,Citigroup Energy Inc,"Sarwar, Adnan",[Jonathan Ching],Banks & Financial Institutions,22-07-2022Dinner with Citigroup in London,{Capital Markets}
7,26-07-2022,Client Entertainment,Drinks with Citibank in New York,Citibank N.A.,"Zion, Isaac",[Christopher Hunker],Banks & Financial Institutions,26-07-2022Drinks with Citibank in New York,{Banking}
8,28-07-2022,Client Entertainment,Lunch with Stanislav Lysikov and Shao-Ling Angoh,Citibank N.A.,"Lysikov, Stanislav",[Unknown],Banks & Financial Institutions,28-07-2022Lunch with Stanislav Lysikov and Sha...,{None}
9,07-07-2022,Client Sponsored Event,Fachgespräch AK Finanztermingeschäfte: Deutsch...,Citigroup Global Markets Europe AG,"Kilian, Dieter; Roth, Frank","[Jörg Fried, Christian Storck, Marc Voelcker]",Banks & Financial Institutions,07-07-2022Fachgespräch AK Finanztermingeschäft...,{Capital Markets}
10,28-07-2022,Client Sponsored Event,Citi Belfast Legal -- 15th Anniversary Charity...,Citibank Europe Plc,"Mackenzie, Stephen","[Leanne Banfield, Simon Few, James Joseph, Han...",Banks & Financial Institutions,28-07-2022Citi Belfast Legal -- 15th Anniversa...,{Capital Markets}
11,28-07-2022,Client Sponsored Event,Citi Belfast Legal -- 15th Anniversary Charity...,Citigroup Capital UK Limited,"Resch, Deborah","[Leanne Banfield, Simon Few, James Joseph, Han...",Retail Asset Managers,28-07-2022Citi Belfast Legal -- 15th Anniversa...,{Capital Markets}
12,21-07-2022,Event - Attended,"Attended: Frankfurter Alumni Feier, 21.07.2022",Citibank Europe Plc,"Jobski, Justus","[Dorothee Barg, Lisa Bauer, Kathrin Bauwens, R...",Banks & Financial Institutions,"21-07-2022Attended: Frankfurter Alumni Feier, ...","{Banking, None, Mainstream Corporate, Capital ..."
13,22-07-2022,Event - Attended,LON_Event_MiFID II ESG Roundtable & Updated ES...,Citibank,"Fernandez Caballero, Bruno; McCaffrey, Sean",[Unknown],Banks & Financial Institutions,22-07-2022LON_Event_MiFID II ESG Roundtable & ...,{None}
14,22-07-2022,Event - Attended,LON_Event_MiFID II ESG Roundtable & Updated ES...,Citigroup Inc.,"Speirs, Rachael",[Unknown],Banks & Financial Institutions,22-07-2022LON_Event_MiFID II ESG Roundtable & ...,{None}
15,05-07-2022,Relationship Meeting,Coryton: Closing Dinner,Citibank,"Ellington, Belinda","[Sinead Crossan, Jeremy Gewirtz, Rebecca Jarvi...",Banks & Financial Institutions,05-07-2022Coryton: Closing Dinner,"{Energy & Infrastructure, Mainstream Corporate..."
16,05-07-2022,Relationship Meeting,Coryton: Closing Dinner,Citibank N.A.,"Rao, Akshay","[Sinead Crossan, Jeremy Gewirtz, Rebecca Jarvi...",Banks & Financial Institutions,05-07-2022Coryton: Closing Dinner,"{Energy & Infrastructure, Mainstream Corporate..."
17,05-07-2022,Relationship Meeting,Coryton: Closing Dinner,Citi Business Services (CBS) Citigroup Centre,"Blot, Laurence","[Sinead Crossan, Jeremy Gewirtz, Rebecca Jarvi...",Banks & Financial Institutions,05-07-2022Coryton: Closing Dinner,"{Energy & Infrastructure, Mainstream Corporate..."
18,05-07-2022,Relationship Meeting,Coryton: Closing Dinner,Citigroup Inc.,"Fisher, Nathan; Griffiths, Alexander; Medcalf,...","[Sinead Crossan, Jeremy Gewirtz, Rebecca Jarvi...",Banks & Financial Institutions,05-07-2022Coryton: Closing Dinner,"{Energy & Infrastructure, Mainstream Corporate..."
19,07-07-2022,Relationship Meeting,"Meeting with Citigroup Global Markets Japan, I...",Citigroup Global Markets Japan Inc.,"Ichise, Kohei; Katayama, Tatsuyori; Nakatsuka,...","[James Inglis, Tracy Whiriskey, Kentaro Yamamura]",Banks & Financial Institutions,07-07-2022Meeting with Citigroup Global Market...,{Mainstream Corporate}
20,13-07-2022,Relationship Meeting,Coffee,Citibank,"Gray, Nathan",[Kristin Da Costa],Banks & Financial Institutions,13-07-2022Coffee,{Capital Markets}
21,20-07-2022,Relationship Meeting,"Meeting: Derek Wilson, Ian Campbell & Melissa ...",Citibank,"Ong, Derek","[Jonathan Horan, Maree Quinn, Amit Singh]",Banks & Financial Institutions,"20-07-2022Meeting: Derek Wilson, Ian Campbell ...",{Capital Markets}
22,20-07-2022,Relationship Meeting,"Meeting: Derek Wilson, Ian Campbell & Melissa ...",Citigroup Inc.,"Campbell, Ian","[Jonathan Horan, Maree Quinn, Amit Singh]",Banks & Financial Institutions,"20-07-2022Meeting: Derek Wilson, Ian Campbell ...",{Capital Markets}
23,20-07-2022,Relationship Meeting,Relationship Meeting,Citigroup Global Markets Europe Limited,"Abel, Richard",[Unknown],Banks & Financial Institutions,20-07-2022Relationship Meeting,{None}
24,20-07-2022,Relationship Meeting,Relationship Meeting,Citigroup Global Markets Limited,"Evans, Patrick",[Unknown],Banks & Financial Institutions,20-07-2022Relationship Meeting,{None}
25,20-07-2022,Relationship Meeting,Linklaters and Citi Lunch,Citibank N.A.,"Dupee, Emily; Hamblin, Jillian; Hughes, Laura;...","[Sarah Cripps, Kristin Da Costa, Stuart Mason,...",Banks & Financial Institutions,20-07-2022Linklaters and Citi Lunch,"{Banking, Capital Markets}"
26,22-07-2022,Relationship Meeting,Coffee catch-up: Peter/Jonathan,Citigroup Inc.,"Asher, Jonathan",[Peter Bevan],Banks & Financial Institutions,22-07-2022Coffee catch-up: Peter/Jonathan,{Financial Regulation Group}
27,25-07-2022,Relationship Meeting,Lunch meeting with Deutsche Indonesia,Citigroup Global Markets Asia Limited,"Lamadjido, Romy",[Adrian Pranata],Banks & Financial Institutions,25-07-2022Lunch meeting with Deutsche Indonesia,{Banking}
28,26-07-2022,Relationship Meeting,Catch up near Citi,Citibank,"Hamilton, Tom",[Elli Karaindrou],Banks & Financial Institutions,26-07-2022Catch up near Citi,{Banking}
29,27-07-2022,Relationship Meeting,Phoenix Natura Gas client visit and lunch with...,Citigroup Inc.,"Quinn, Jo","[Emma Crawford, Natura Gracia, Reza Taylor, Je...",Banks & Financial Institutions,27-07-2022Phoenix Natura Gas client visit and ...,"{Antitrust & Foreign Investment Group, Capital..."
30,27-07-2022,Relationship Meeting,Breakfast,Citigroup Inc.,"Esguevillas Lete, Luis",[Iñigo Berricano],Banks & Financial Institutions,27-07-2022Breakfast,{Capital Markets}
31,27-07-2022,Relationship Meeting,Lunch,Citibank,"Hamilton, Tom",[Elli Karaindrou],Banks & Financial Institutions,27-07-2022Lunch,{Banking}
32,19-07-2022,Training and Seminar - Delivered,Citi GRIP training followed by drinks,Citigroup Global Markets Inc.,"Bendernagel, Donald; Bentch, Adam; Hales, Shannon","[Leanne Banfield, Andrew Kummer, Ruhi Patil, D...",Banks & Financial Institutions,19-07-2022Citi GRIP training followed by drinks,{Capital Markets}
33,19-07-2022,Training and Seminar - Delivered,Citi GRIP training followed by drinks,Citigroup Inc.,"Chandra, Seema","[Leanne Banfield, Andrew Kummer, Ruhi Patil, D...",Banks & Financial Institutions,19-07-2022Citi GRIP training followed by drinks,{Capital Markets}

In [247]:
df4 = pd.DataFrame(df3.groupby('Concat',as_index=False).agg(lambda x: '; '.join(set(x))))

In [248]:
df4['Client Contacts'] = df4['Client Contacts'].str.split('; ')

In [249]:
for x in df4['Client Contacts']:
  for n in range(len(x)):
    x[n] = " ".join(x[n].split(", ")[::-1])

for n in range(len(df4['Client Contacts'])):
  if len(df4['Client Contacts'][n]) in range(2,5):
    df4['Client Contacts'][n] = ', '.join(df4['Client Contacts'][n])
    k = df4['Client Contacts'][n].rfind(',')
    df4['Client Contacts'][n] = df4['Client Contacts'][n][:k] + ' and' + df4['Client Contacts'][n][k+1:]
  elif len(df4['Client Contacts'][n]) > 4:
    df4['Client Contacts'][n] = 'a few members from your team'
  else:
    df4['Client Contacts'][n] = ', '.join(df4['Client Contacts'][n])

In [250]:
df4['Linklaters Contacts'] = df4['Linklaters Contacts'].str.split('; ')

for x in df4['Linklaters Contacts']:
  for n in range(len(x)):
    x[n] = " ".join(x[n].split(", ")[::-1])

for n in range(len(df4['Linklaters Contacts'])):
  if len(df4['Linklaters Contacts'][n]) in range(2,5):
    df4['Linklaters Contacts'][n] = ', '.join(df4['Linklaters Contacts'][n])
    k = df4['Linklaters Contacts'][n].rfind(',')
    df4['Linklaters Contacts'][n] = df4['Linklaters Contacts'][n][:k] + ' and' + df4['Linklaters Contacts'][n][k+1:]
  elif len(df4['Linklaters Contacts'][n]) > 4:
    df4['Linklaters Contacts'][n] = 'a few of our lawyers'
  else:
    df4['Linklaters Contacts'][n] = ', '.join(df4['Linklaters Contacts'][n])

In [251]:
df4 = df4.merge(staff, left_on='Linklaters Contacts', right_on='Name',how='left')
df4['Individual'] = df4['Individual'].astype('Int32',errors='ignore')

In [252]:
df4

,Concat,Activity Date,Activity Type,Summary,Client,Client Contacts,Linklaters Contacts,Sector,Individual,Name,Office,Practice/BS Group,No. of Records
0,05-07-2022Coryton: Closing Dinner,05-07-2022,Relationship Meeting,Coryton: Closing Dinner,Citi Business Services (CBS) Citigroup Centre;...,a few members from your team,a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
1,07-07-2022Fachgespräch AK Finanztermingeschäft...,07-07-2022,Client Sponsored Event,Fachgespräch AK Finanztermingeschäfte: Deutsch...,Citigroup Global Markets Europe AG,Dieter Kilian and Frank Roth,"Jörg Fried, Christian Storck and Marc Voelcker",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
2,07-07-2022Lunch catch-up,07-07-2022,Client Entertainment,Lunch catch-up,Citigroup Inc.,Wan Sang Lung,Thomas Shen,Banks & Financial Institutions,929605,Thomas Shen,London,Capital Markets,1.0
3,07-07-2022Lunch with Shaalini and Mikhail,07-07-2022,Client Entertainment,Lunch with Shaalini and Mikhail,Citi Business Services (CBS) Citigroup Centre,Shaalini Daya,Mikhail Shiyan,Banks & Financial Institutions,951297,Mikhail Shiyan,London,Banking,1.0
4,07-07-2022Meeting with Citigroup Global Market...,07-07-2022,Relationship Meeting,"Meeting with Citigroup Global Markets Japan, I...",Citigroup Global Markets Japan Inc.,"Kohei Ichise, Tatsuyori Katayama, Kensuke Naka...","James Inglis, Tracy Whiriskey and Kentaro Yama...",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
5,13-07-2022Coffee,13-07-2022,Relationship Meeting,Coffee,Citibank,Nathan Gray,Kristin Da Costa,Banks & Financial Institutions,944207,Kristin Da Costa,London,Capital Markets,1.0
6,14-07-2022Dinner: Noel Hughes and Tommaso Pons...,14-07-2022,Client Entertainment,Dinner: Noel Hughes and Tommaso Ponsele (Citi),Citigroup Inc.,Tommaso Ponsele,Noel Hughes,Banks & Financial Institutions,956638,Noel Hughes,London,Banking,1.0
7,19-07-2022Citi GRIP training followed by drinks,19-07-2022,Training and Seminar - Delivered,Citi GRIP training followed by drinks,Citigroup Global Markets Inc.; Citigroup Inc.,"Seema Chandra, Donald Bendernagel, Adam Bentch...",a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
8,20-07-2022Drinks with Citibank in London,20-07-2022,Client Entertainment,Drinks with Citibank in London,Citi Business Services (CBS) Citigroup Centre;...,"Aliona Chakhvadze, Elena Jigarjian and Belinda...",Jonathan Ching,Banks & Financial Institutions,939039,Jonathan Ching,New York,Capital Markets,1.0
9,20-07-2022Linklaters and Citi Lunch,20-07-2022,Relationship Meeting,Linklaters and Citi Lunch,Citibank N.A.,a few members from your team,a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
10,"20-07-2022Meeting: Derek Wilson, Ian Campbell ...",20-07-2022,Relationship Meeting,"Meeting: Derek Wilson, Ian Campbell & Melissa ...",Citigroup Inc.; Citibank,Derek Ong and Ian Campbell,"Jonathan Horan, Maree Quinn and Amit Singh",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
11,20-07-2022Relationship Meeting,20-07-2022,Relationship Meeting,Relationship Meeting,Citigroup Global Markets Europe Limited; Citig...,Patrick Evans and Richard Abel,Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
12,"21-07-2022Attended: Frankfurter Alumni Feier, ...",21-07-2022,Event - Attended,"Attended: Frankfurter Alumni Feier, 21.07.2022",Citibank Europe Plc,Justus Jobski,a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
13,21-07-2022Breakfast,21-07-2022,Client Entertainment,Breakfast,Citigroup Global Markets Europe Limited,Colin Cooke,Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
14,22-07-2022Coffee catch-up: Peter/Jonathan,22-07-2022,Relationship Meeting,Coffee catch-up: Peter/Jonathan,Citigroup Inc.,Jonathan Asher,Peter Bevan,Banks & Financial Institutions,903957,Peter Bevan,London,Financial Regulation Group,1.0
15,22-07-2022Dinner with Citigroup in London,22-07-2022,Client Entertainment,Dinner with Citigroup in London,Citigroup Energy Inc,Adnan Sarwar,Jonathan Ching,Banks & Financial Institutions,939039,Jonathan Ching,New York,Capital Markets,1.0
16,22-07-2022LON_Event_MiFID II ESG Roundtable & ...,22-07-2022,Event - Attended,LON_Event_MiFID II ESG Roundtable & Updated ES...,Citigroup Inc.; Citibank,"Rachael Speirs, Bruno Fernandez Caballero and ...",Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
17,25-07-2022Lunch meeting with Deutsche Indonesia,25-07-2022,Relationship Meeting,Lunch meeting with Deutsche Indonesia,Citigroup Global Markets Asia Limited,Romy Lamadjido,Adrian Pranata,Banks & Financial Institutions,939305,Adrian Pranata,Indonesia Jakarta,Banking,1.0
18,26-07-2022Catch up near Citi,26-07-2022,Relationship Meeting,Catch up near Citi,Citibank,Tom Hamilton,Elli Karaindrou,Banks & Financial Institutions,941817,Elli Karaindrou,London,Banking,1.0
19,26-07-2022Drinks with Citibank in New York,26-07-2022,Client Entertainment,Drinks with Citibank in New York,Citibank N.A.,Isaac Zion,Christopher Hunker,Banks & Financial Institutions,939437,Christopher Hunker,New York,Banking,1.0
20,27-07-2022Breakfast,27-07-2022,Relationship Meeting,Breakfast,Citigroup Inc.,Luis Esguevillas Lete,Iñigo Berricano,Banks & Financial Institutions,905337,Iñigo Berricano,Madrid,Capital Markets,1.0
21,27-07-2022Lunch,27-07-2022,Relationship Meeting,Lunch,Citibank,Tom Hamilton,Elli Karaindrou,Banks & Financial Institutions,941817,Elli Karaindrou,London,Banking,1.0
22,27-07-2022Phoenix Natura Gas client visit and ...,27-07-2022,Relationship Meeting,Phoenix Natura Gas client visit and lunch with...,Citigroup Inc.,Jo Quinn,"Emma Crawford, Natura Gracia, Reza Taylor and ...",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN
23,28-07-2022Citi Belfast Legal -- 15th Anniversa...,28-07-2022,Client Sponsored Event,Citi Belfast Legal -- 15th Anniversary Charity...,Citigroup Capital UK Limited; Citibank Europe Plc,Stephen Mackenzie and Deborah Resch,"Leanne Banfield, Simon Few, James Joseph and H...",Banks & Financial Institutions; Retail Asset M...,<NA>,NaN,NaN,NaN,NaN
24,28-07-2022Lunch with Stanislav Lysikov and Sha...,28-07-2022,Client Entertainment,Lunch with Stanislav Lysikov and Shao-Ling Angoh,Citibank N.A.,Stanislav Lysikov,Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN

In [253]:
from datetime import datetime

In [254]:
def final():
  narratives = {}

  for x in range(len(df4)):
    if df4['Activity Type'][x] in(['Client Entertainment', 'Relationship Meeting']):  
      narratives.update({df4['Concat'][x] : f'{df4["Linklaters Contacts"][x][0].upper() + df4["Linklaters Contacts"][x][1:]} met with {df4["Client Contacts"][x]} on {datetime.strptime(df4["Activity Date"][x], "%d-%m-%Y").date().strftime("%-d %B")}'})
    elif df4['Activity Type'][x] in (['Training and Seminar - Delivered','Client Sponsored Event']):
      narratives.update({df4['Concat'][x] : f'{df4["Linklaters Contacts"][x][0].upper() + df4["Linklaters Contacts"][x][1:]} attended the {df4["Summary"][x]} on {datetime.strptime(df4["Activity Date"][x], "%d-%m-%Y").date().strftime("%-d %B")}'})
    else:
      narratives.update({df4['Concat'][x] : f'{df4["Client Contacts"][x][0].upper() + df4["Client Contacts"][x][1:]} attended the {df4["Summary"][x]} on {datetime.strptime(df4["Activity Date"][x], "%d-%m-%Y").date().strftime("%-d %B")}'})
  return narratives

In [255]:
final()

{'05-07-2022Coryton: Closing Dinner': 'A few of our lawyers met with a few members from your team on 5 July',
 '07-07-2022Fachgespräch AK Finanztermingeschäfte: Deutsche Rahmenverträge und Rechtsentwicklungen 2022': 'Jörg Fried, Christian Storck and Marc Voelcker attended the Fachgespräch AK Finanztermingeschäfte: Deutsche Rahmenverträge und Rechtsentwicklungen 2022 on 7 July',
 '07-07-2022Lunch catch-up': 'Thomas Shen met with Wan Sang Lung on 7 July',
 '07-07-2022Lunch with Shaalini and Mikhail': 'Mikhail Shiyan met with Shaalini Daya on 7 July',
 '07-07-2022Meeting with Citigroup Global Markets Japan, Inc. (Japan marketing trip)': 'James Inglis, Tracy Whiriskey and Kentaro Yamamura met with Kohei Ichise, Tatsuyori Katayama, Kensuke Nakatsuka and Tesshu Takeuchi on 7 July',
 '13-07-2022Coffee': 'Kristin Da Costa met with Nathan Gray on 13 July',
 '14-07-2022Dinner: Noel Hughes and Tommaso Ponsele (Citi)': 'Noel Hughes met with Tommaso Ponsele on 14 July',
 '19-07-2022Citi GRIP training followed by drinks': 'A few of our lawyers attended the Citi GRIP training followed by drinks on 19 July',
 '20-07-2022Drinks with Citibank in London': 'Jonathan Ching met with Aliona Chakhvadze, Elena Jigarjian and Belinda Ellington on 20 July',
 '20-07-2022Linklaters and Citi Lunch': 'A few of our lawyers met with a few members from your team on 20 July',
 '20-07-2022Meeting: Derek Wilson, Ian Campbell & Melissa Carmody (of Citigroup), James Darcy (of Allens) and Amit Singh, Jonathan Horan & Maree Quinn (of Linklaters)': 'Jonathan Horan, Maree Quinn and Amit Singh met with Derek Ong and Ian Campbell on 20 July',
 '20-07-2022Relationship Meeting': 'Unknown met with Patrick Evans and Richard Abel on 20 July',
 '21-07-2022Attended: Frankfurter Alumni Feier, 21.07.2022': 'Justus Jobski attended the Attended: Frankfurter Alumni Feier, 21.07.2022 on 21 July',
 '21-07-2022Breakfast': 'Unknown met with Colin Cooke on 21 July',
 '22-07-2022Coffee catch-up: Peter/Jonathan': 'Peter Bevan met with Jonathan Asher on 22 July',
 '22-07-2022Dinner with Citigroup in London': 'Jonathan Ching met with Adnan Sarwar on 22 July',
 '22-07-2022LON_Event_MiFID II ESG Roundtable & Updated ESMA Product Governance G - Event attended': 'Rachael Speirs, Bruno Fernandez Caballero and Sean McCaffrey attended the LON_Event_MiFID II ESG Roundtable & Updated ESMA Product Governance G - Event attended on 22 July',
 '25-07-2022Lunch meeting with Deutsche Indonesia': 'Adrian Pranata met with Romy Lamadjido on 25 July',
 '26-07-2022Catch up near Citi': 'Elli Karaindrou met with Tom Hamilton on 26 July',
 '26-07-2022Drinks with Citibank in New York': 'Christopher Hunker met with Isaac Zion on 26 July',
 '27-07-2022Breakfast': 'Iñigo Berricano met with Luis Esguevillas Lete on 27 July',
 '27-07-2022Lunch': 'Elli Karaindrou met with Tom Hamilton on 27 July',
 '27-07-2022Phoenix Natura Gas client visit and lunch with Michael McKinstry, Kailash Chada and Joanne Quinn': 'Emma Crawford, Natura Gracia, Reza Taylor and Jennifer Willis met with Jo Quinn on 27 July',
 '28-07-2022Citi Belfast Legal -- 15th Anniversary Charity Formal': 'Leanne Banfield, Simon Few, James Joseph and Hannah Pilkington attended the Citi Belfast Legal -- 15th Anniversary Charity Formal on 28 July',
 '28-07-2022Lunch with Stanislav Lysikov and Shao-Ling Angoh': 'Unknown met with Stanislav Lysikov on 28 July'}

In [256]:
df_narratives = pd.DataFrame.from_dict(final(),orient='index',columns=['Narrative'])

In [257]:
df_final = df4.merge(df_narratives, left_on='Concat', right_index = True,how='left')

In [258]:
df_final

,Concat,Activity Date,Activity Type,Summary,Client,Client Contacts,Linklaters Contacts,Sector,Individual,Name,Office,Practice/BS Group,No. of Records,Narrative
0,05-07-2022Coryton: Closing Dinner,05-07-2022,Relationship Meeting,Coryton: Closing Dinner,Citi Business Services (CBS) Citigroup Centre;...,a few members from your team,a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,A few of our lawyers met with a few members fr...
1,07-07-2022Fachgespräch AK Finanztermingeschäft...,07-07-2022,Client Sponsored Event,Fachgespräch AK Finanztermingeschäfte: Deutsch...,Citigroup Global Markets Europe AG,Dieter Kilian and Frank Roth,"Jörg Fried, Christian Storck and Marc Voelcker",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,"Jörg Fried, Christian Storck and Marc Voelcker..."
2,07-07-2022Lunch catch-up,07-07-2022,Client Entertainment,Lunch catch-up,Citigroup Inc.,Wan Sang Lung,Thomas Shen,Banks & Financial Institutions,929605,Thomas Shen,London,Capital Markets,1.0,Thomas Shen met with Wan Sang Lung on 7 July
3,07-07-2022Lunch with Shaalini and Mikhail,07-07-2022,Client Entertainment,Lunch with Shaalini and Mikhail,Citi Business Services (CBS) Citigroup Centre,Shaalini Daya,Mikhail Shiyan,Banks & Financial Institutions,951297,Mikhail Shiyan,London,Banking,1.0,Mikhail Shiyan met with Shaalini Daya on 7 July
4,07-07-2022Meeting with Citigroup Global Market...,07-07-2022,Relationship Meeting,"Meeting with Citigroup Global Markets Japan, I...",Citigroup Global Markets Japan Inc.,"Kohei Ichise, Tatsuyori Katayama, Kensuke Naka...","James Inglis, Tracy Whiriskey and Kentaro Yama...",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,"James Inglis, Tracy Whiriskey and Kentaro Yama..."
5,13-07-2022Coffee,13-07-2022,Relationship Meeting,Coffee,Citibank,Nathan Gray,Kristin Da Costa,Banks & Financial Institutions,944207,Kristin Da Costa,London,Capital Markets,1.0,Kristin Da Costa met with Nathan Gray on 13 July
6,14-07-2022Dinner: Noel Hughes and Tommaso Pons...,14-07-2022,Client Entertainment,Dinner: Noel Hughes and Tommaso Ponsele (Citi),Citigroup Inc.,Tommaso Ponsele,Noel Hughes,Banks & Financial Institutions,956638,Noel Hughes,London,Banking,1.0,Noel Hughes met with Tommaso Ponsele on 14 July
7,19-07-2022Citi GRIP training followed by drinks,19-07-2022,Training and Seminar - Delivered,Citi GRIP training followed by drinks,Citigroup Global Markets Inc.; Citigroup Inc.,"Seema Chandra, Donald Bendernagel, Adam Bentch...",a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,A few of our lawyers attended the Citi GRIP tr...
8,20-07-2022Drinks with Citibank in London,20-07-2022,Client Entertainment,Drinks with Citibank in London,Citi Business Services (CBS) Citigroup Centre;...,"Aliona Chakhvadze, Elena Jigarjian and Belinda...",Jonathan Ching,Banks & Financial Institutions,939039,Jonathan Ching,New York,Capital Markets,1.0,"Jonathan Ching met with Aliona Chakhvadze, Ele..."
9,20-07-2022Linklaters and Citi Lunch,20-07-2022,Relationship Meeting,Linklaters and Citi Lunch,Citibank N.A.,a few members from your team,a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,A few of our lawyers met with a few members fr...
10,"20-07-2022Meeting: Derek Wilson, Ian Campbell ...",20-07-2022,Relationship Meeting,"Meeting: Derek Wilson, Ian Campbell & Melissa ...",Citigroup Inc.; Citibank,Derek Ong and Ian Campbell,"Jonathan Horan, Maree Quinn and Amit Singh",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,"Jonathan Horan, Maree Quinn and Amit Singh met..."
11,20-07-2022Relationship Meeting,20-07-2022,Relationship Meeting,Relationship Meeting,Citigroup Global Markets Europe Limited; Citig...,Patrick Evans and Richard Abel,Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,Unknown met with Patrick Evans and Richard Abe...
12,"21-07-2022Attended: Frankfurter Alumni Feier, ...",21-07-2022,Event - Attended,"Attended: Frankfurter Alumni Feier, 21.07.2022",Citibank Europe Plc,Justus Jobski,a few of our lawyers,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,Justus Jobski attended the Attended: Frankfurt...
13,21-07-2022Breakfast,21-07-2022,Client Entertainment,Breakfast,Citigroup Global Markets Europe Limited,Colin Cooke,Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,Unknown met with Colin Cooke on 21 July
14,22-07-2022Coffee catch-up: Peter/Jonathan,22-07-2022,Relationship Meeting,Coffee catch-up: Peter/Jonathan,Citigroup Inc.,Jonathan Asher,Peter Bevan,Banks & Financial Institutions,903957,Peter Bevan,London,Financial Regulation Group,1.0,Peter Bevan met with Jonathan Asher on 22 July
15,22-07-2022Dinner with Citigroup in London,22-07-2022,Client Entertainment,Dinner with Citigroup in London,Citigroup Energy Inc,Adnan Sarwar,Jonathan Ching,Banks & Financial Institutions,939039,Jonathan Ching,New York,Capital Markets,1.0,Jonathan Ching met with Adnan Sarwar on 22 July
16,22-07-2022LON_Event_MiFID II ESG Roundtable & ...,22-07-2022,Event - Attended,LON_Event_MiFID II ESG Roundtable & Updated ES...,Citigroup Inc.; Citibank,"Rachael Speirs, Bruno Fernandez Caballero and ...",Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,"Rachael Speirs, Bruno Fernandez Caballero and ..."
17,25-07-2022Lunch meeting with Deutsche Indonesia,25-07-2022,Relationship Meeting,Lunch meeting with Deutsche Indonesia,Citigroup Global Markets Asia Limited,Romy Lamadjido,Adrian Pranata,Banks & Financial Institutions,939305,Adrian Pranata,Indonesia Jakarta,Banking,1.0,Adrian Pranata met with Romy Lamadjido on 25 July
18,26-07-2022Catch up near Citi,26-07-2022,Relationship Meeting,Catch up near Citi,Citibank,Tom Hamilton,Elli Karaindrou,Banks & Financial Institutions,941817,Elli Karaindrou,London,Banking,1.0,Elli Karaindrou met with Tom Hamilton on 26 July
19,26-07-2022Drinks with Citibank in New York,26-07-2022,Client Entertainment,Drinks with Citibank in New York,Citibank N.A.,Isaac Zion,Christopher Hunker,Banks & Financial Institutions,939437,Christopher Hunker,New York,Banking,1.0,Christopher Hunker met with Isaac Zion on 26 July
20,27-07-2022Breakfast,27-07-2022,Relationship Meeting,Breakfast,Citigroup Inc.,Luis Esguevillas Lete,Iñigo Berricano,Banks & Financial Institutions,905337,Iñigo Berricano,Madrid,Capital Markets,1.0,Iñigo Berricano met with Luis Esguevillas Lete...
21,27-07-2022Lunch,27-07-2022,Relationship Meeting,Lunch,Citibank,Tom Hamilton,Elli Karaindrou,Banks & Financial Institutions,941817,Elli Karaindrou,London,Banking,1.0,Elli Karaindrou met with Tom Hamilton on 27 July
22,27-07-2022Phoenix Natura Gas client visit and ...,27-07-2022,Relationship Meeting,Phoenix Natura Gas client visit and lunch with...,Citigroup Inc.,Jo Quinn,"Emma Crawford, Natura Gracia, Reza Taylor and ...",Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,"Emma Crawford, Natura Gracia, Reza Taylor and ..."
23,28-07-2022Citi Belfast Legal -- 15th Anniversa...,28-07-2022,Client Sponsored Event,Citi Belfast Legal -- 15th Anniversary Charity...,Citigroup Capital UK Limited; Citibank Europe Plc,Stephen Mackenzie and Deborah Resch,"Leanne Banfield, Simon Few, James Joseph and H...",Banks & Financial Institutions; Retail Asset M...,<NA>,NaN,NaN,NaN,NaN,"Leanne Banfield, Simon Few, James Joseph and H..."
24,28-07-2022Lunch with Stanislav Lysikov and Sha...,28-07-2022,Client Entertainment,Lunch with Stanislav Lysikov and Shao-Ling Angoh,Citibank N.A.,Stanislav Lysikov,Unknown,Banks & Financial Institutions,<NA>,NaN,NaN,NaN,NaN,Unknown met with Stanislav Lysikov on 28 July